language: c
compiler:
 - gcc
os:
 - linux
script:
    gcc -o work/task1 work/task1.c work/main1.c -lm && gcc -o work/task2 work/task2.c work/main2.c && gcc -o work/task3 work/task3.c work/main3.c && gcc -o work/task4 work/task4.c work/main4.c && gcc -o work/task5 work/task5.c work/main5.c && gcc -o work/task6 work/task6.c work/main6.c && gcc -o work/task7 work/main7.c
